dist: xenial

language: r

r:
  - "3.6"

sudo: required

install:
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo apt-get update
  - sudo -H apt-get -y install git libssh2-1-dev cmake build-essential libgit2-dev python3.6-dev
  - curl https://bootstrap.pypa.io/get-pip.py | sudo -H python3.6

script:
  - python3.6 -m pip install --user -e .
  -  LD_LIBRARY_PATH=/opt/R/3.6.3/lib/R/library/:/home/travis/R-bin/lib/R/lib/:${LD_LIBRARY_PATH} cosifer -h
